// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!

/* tslint:disable */
/* eslint-disable */
{%- if !module.strict_type_checking %}
// @ts-nocheck
{%- endif %}
{#- Import a type only when this file uses it. The future types are used
    only by the JSI checks at the end of the file. #}
{%- if module.is_jsi || module.core_types.any() %}

import {
  {%- if module.is_jsi && (module.has_continuation_callback || module.has_foreign_future) %}
  type StructuralEquality as UniffiStructuralEquality,
  {%- endif %}
  {%- if module.is_jsi && module.has_foreign_future %}
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  {%- endif %}
  {%- if module.core_types.rust_call_status %}
  type UniffiRustCallStatus,
  {%- endif %}
  {%- if module.core_types.gc_object %}
  type UniffiGcObject,
  {%- endif %}
  {%- if module.is_jsi && module.has_continuation_callback %}
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  {%- endif %}
  {%- if module.core_types.result %}
  type UniffiResult,
  {%- endif %}
 } from '@ubjs/core';
{%- endif %}
{%- if module.is_jsi %}

interface NativeModuleInterface {
    {%- for func in module.functions %}
    {{ func.name }}(
      {%- for arg in func.arguments %}
        {{- arg.name }}: {{ arg.type_name }}
        {%- if !loop.last %}, {% endif %}
      {%- endfor %}):
      {%- match func.return_type %}{% when Some with (rt) %} {{ rt }}{% when None %} void{% endmatch %};
  {%- endfor %}
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The JSI host object exposes
    // them as properties; see `props["rustbuffer_alloc"]` / `props["rustbuffer_free"]`
    // in the C++ wrapper template.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

const getter: () => NativeModuleInterface = () => (globalThis as any).{{ module.module_name }};
export default getter;
{%- endif %}

// Structs and function types for calling back into Typescript from Rust.
{%- for def in module.definitions %}
{%- match def %}
{%- when FfiDefinitionDecl::Callback(callback) %}
{% if callback.exported %}export {% endif %}type {{ callback.name }} = (
{%-   for arg in callback.arguments %}
{{- arg.name }}: {{ arg.type_name }}{% if !loop.last %}, {% endif %}
{%-   endfor %}) => {{ callback.return_type }};
{%- when FfiDefinitionDecl::Struct(ffi_struct) %}
{% if ffi_struct.exported %}export {% endif %}type {{ ffi_struct.name }} = {
  {%- for field in ffi_struct.fields %}
  {{ field.name }}: {{ field.type_name }};
  {%- endfor %}
};
{%- endmatch %}
{%- endfor %}
{%- if module.is_jsi %}
{#- uniffi-rs 0.32 declares the future types only for a module that uses
    async, so write each check, and its comment, only when there is a type
    to check. #}
{%- if module.has_continuation_callback %}

// UniffiRustFutureContinuationCallback is generated as part of the component interface's
// ffi_definitions. However, we need it in the runtime.
// We chose to generate the declaration anyway, and use a different declaration in the runtime.
// We perform a compile time check that the two versions are structurally equivalent.
const isRustFutureContinuationCallbackTypeCompatible: UniffiStructuralEquality<
  RuntimeUniffiRustFutureContinuationCallback,
  UniffiRustFutureContinuationCallback
> = true;
{%- endif %}
{%- if module.has_foreign_future %}
const isUniffiForeignFutureTypeCompatible: UniffiStructuralEquality<
  RuntimeUniffiForeignFuture,
  UniffiForeignFuture
> = true;
{%- endif %}
{%- endif %}
